version: 2.1

jobs:
  install:
    docker:
      - image: node:lts
    steps:
      - checkout
      - run: npm ci
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
  curl_testing:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: |
          docker build -t tp_ci_docker:SNAPSHOT .
          docker run -d -p 8080:8080 tp_ci_docker:SNAPSHOT
      - run: |
          curl -v http://localhost:8080/users

  publish:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: |
          docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
          docker build -t MehdiSaadi/Tp_CI_Docker .
          docker push MehdiSaadi/Tp_CI_Docker
workflows:
  version: 2
  custom_workflow:
    jobs:
      - install
      - curl_testing:
          requires:
            - install
      - publish:
          requires:
            - curl_testing